# config/settings.yaml

activity_directory: activities
state_variables:
  energy:
    initial: 100
    min: 0
    max: 100
  happiness:
    initial: 50
    min: 0
    max: 100
  xp:
    initial: 0
    min: 0
    max: null
